"""TIME BUDGET: 20 minutes, plus the calibration below.

Do this SECOND: nothing can be retrieved until it is done.

THE CALIBRATION IS NOT OPTIONAL. The distance numbers in POLICY are copied from
a different corpus and WILL be wrong for yours. Procedure, ~20 minutes:

    DOMAIN=<name> uv run python -m agentcore.rag.index --reset
    DOMAIN=<name> uv run python -m evaluation.calibrate

Real questions cluster low, nonsense clusters high. Put max_distance in the
GAP between them. Skip this and the system either refuses everything or grounds
on noise - and it presents as a prompt problem, which is where the afternoon
goes.
"""

from __future__ import annotations

from pathlib import Path

from agentcore.contracts import Corpus, GraphQuery, RetrievalPolicy
from agentcore.rag.chunking import MARKDOWN_HEADING, Section, markdown_sections

DOCS = Path(__file__).parent / "docs"

CORPUS = Corpus(
    # Drop your files into docs/. PDF, .md and .txt all work.
    paths=[str(p) for p in sorted(DOCS.glob("*")) if p.is_file()],
    collection="_template",  # CHANGE THIS - it names the database collection
    chunk_size=1200,         # ~300 tokens. Go smaller for dense reference text.
    chunk_overlap=150,       # ~12%: enough to survive a bad boundary
)

POLICY = RetrievalPolicy(
    k=4,
    max_distance=0.70,     # <-- CALIBRATE. See the module docstring.
    relative_margin=0.12,
    # If the corpus has two kinds of content and one is more authoritative,
    # filter to it. On the reference corpus that was worth +36 points of
    # recall@1 - more than any prompt change achieved.
    metadata_filter=None,
    # Locator words a user might type: "article 12", "step 4", "clause 9".
    # 'page' and 'chunk' always work and do not need listing here.
    locators=[],
)

# Optional. Leave {} and the graph arm is never registered - no flag needed,
# the router simply cannot offer a tool that does not exist.
# Cypher is written BY A HUMAN and parameterised. Never generated by a model.
GRAPH_QUERIES: dict[str, GraphQuery] = {}


def is_heading(line: str) -> bool:
    """Must agree with find_sections().

    A heading this function misses can be deleted by boilerplate removal as
    repeated furniture, which silently collapses the document into a handful of
    huge sections. The chunker raises if the heading count drops, so you will
    hear about it - but getting these two consistent is the real fix.
    """
    return bool(MARKDOWN_HEADING.match(line.strip()))


def find_sections(markdown: str) -> list[Section]:
    """How this corpus is cut into structural units.

    The default splits on markdown headings and is right for most documents.
    Override ONLY if the corpus has real structure worth preserving - numbered
    articles, clauses, SOP steps. domains/sample_policy/corpus.py is a worked
    example that tracks two different kinds of section and records a number for
    each, which is what makes "article 33" work as a lookup.
    """
    return markdown_sections(markdown)
